CRITICAL - 2021-08-01 20:33:33,257 - __main__ - restore.main - MainThread - Exception TypeError with message "_check_files() takes 1 positional argument but 2 were given" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:87
WARNING - 2021-08-01 20:51:42,384 - __main__ - restore.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:85
CRITICAL - 2021-08-01 21:03:56,304 - __main__ - restore.main - MainThread - Exception AttributeError with message "'list' object has no attribute 'setdefault'" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:87
CRITICAL - 2021-08-01 21:04:57,111 - __main__ - restore.main - MainThread - Exception AttributeError with message "'list' object has no attribute 'setdefault'" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:87
CRITICAL - 2021-08-01 21:06:35,813 - __main__ - restore.main - MainThread - Exception AttributeError with message "'list' object has no attribute 'setdefault'" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:87
WARNING - 2021-08-01 21:07:09,698 - __main__ - restore.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:80
WARNING - 2021-08-01 21:07:54,120 - __main__ - restore.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:80
WARNING - 2021-08-01 21:08:33,049 - __main__ - restore.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:80
CRITICAL - 2021-08-01 21:13:41,100 - __main__ - restore.main - MainThread - Exception TypeError with message "__init__() got an unexpected keyword argument 'dect'" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:82
CRITICAL - 2021-08-01 21:14:13,016 - __main__ - restore.main - MainThread - Exception TypeError with message "__init__() got an unexpected keyword argument 'dect'" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:76
CRITICAL - 2021-08-01 21:15:01,687 - __main__ - restore.main - MainThread - Exception ValueError with message "too many values to unpack (expected 2)" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:77
WARNING - 2021-08-01 21:19:17,909 - __main__ - restore.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:72
CRITICAL - 2021-08-01 21:19:56,023 - __main__ - restore.main - MainThread - Exception AttributeError with message "'list' object has no attribute 'items'" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:77
WARNING - 2021-08-01 21:22:50,044 - __main__ - restore.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:72
CRITICAL - 2021-08-01 21:24:07,951 - __main__ - restore.main - MainThread - Exception AttributeError with message "'str' object has no attribute 'startwith'" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:77
CRITICAL - 2021-08-01 21:35:18,341 - __main__ - restore.main - MainThread - Exception FileNotFoundError with message "[Errno 2] No such file or directory: '/Users/rkrivov/Parallels/Windows 10.pvm/Windows 10.app/Contents/Info.plist.6c0c796a'" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:77
WARNING - 2021-08-01 21:37:44,457 - __main__ - restore.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:72
WARNING - 2021-08-01 23:54:25,519 - __main__ - restore.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:76
WARNING - 2021-08-01 23:58:38,329 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:135
WARNING - 2021-08-01 23:58:43,468 - __main__ - restore.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/restore.py:72
WARNING - 2021-08-01 23:58:43,525 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:142
WARNING - 2021-08-02 09:44:50,386 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:142
WARNING - 2021-08-02 09:45:51,423 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:135
WARNING - 2021-08-02 09:46:43,854 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:142
WARNING - 2021-08-02 09:51:05,117 - s3.base - base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/VmInfo.pvi[4m[0;39m was changed: The size of the remote file ([0;36m[1m33.16 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m32.43 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-01 09:06:20[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 06:50:23[22m[0;39m), and the ETag of the remote file ([0;36m[1md47360d33e4969e12da8c91b7ec7536a[22m[0;39m) differs from the ETag of the local file ([0;36m[1mf37f51bca917f2f7a2c793a0359b4cf7[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/base.py:263
WARNING - 2021-08-02 09:51:13,468 - s3.base - base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/config.pvs[4m[0;39m was changed: The size of the remote file ([0;36m[1m33.18 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m33.10 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-01 14:20:07[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 06:50:23[22m[0;39m), and the ETag of the remote file ([0;36m[1m9a753aa8d0198ffc9a7b188ceea21841[22m[0;39m) differs from the ETag of the local file ([0;36m[1m7809c5caaee28288582c01fa1deb4035[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/base.py:263
WARNING - 2021-08-02 09:51:13,485 - s3.base - base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/statistic.log[4m[0;39m was changed: The size of the remote file ([0;36m[1m3.70 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m3.70 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-01 14:20:07[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 06:50:24[22m[0;39m), and the ETag of the remote file ([0;36m[1me41f200834af85a34df13f5eeb02b678[22m[0;39m) differs from the ETag of the local file ([0;36m[1m9cc3e03874af7fd107dca3e9c270e9b3[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/base.py:263
WARNING - 2021-08-02 09:51:13,487 - s3.base - base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/config.pvs.backup[4m[0;39m was changed: The size of the remote file ([0;36m[1m33.18 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m33.10 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-01 14:20:07[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 06:50:23[22m[0;39m), and the ETag of the remote file ([0;36m[1m9a753aa8d0198ffc9a7b188ceea21841[22m[0;39m) differs from the ETag of the local file ([0;36m[1m7809c5caaee28288582c01fa1deb4035[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/base.py:263
WARNING - 2021-08-02 09:51:13,524 - s3.base - base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/parallels.log[4m[0;39m was changed: The size of the remote file ([0;36m[1m8.57 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m8.69 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-01 09:06:25[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 06:50:23[22m[0;39m), and the ETag of the remote file ([0;36m[1m596b6d3795927861e85b12bb6f1a374c[22m[0;39m) differs from the ETag of the local file ([0;36m[1m0d4d61b14d810e0b53216ff8c6476568[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/base.py:263
WARNING - 2021-08-02 09:51:39,756 - s3.base - base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/harddisk.hdd/harddisk.hdd.0.{5fbaabe3-6958-40ff-92a7-860e329aab41}.hds[4m[0;39m was changed: The size of the remote file ([0;36m[1m2.90 GB[22m[0;39m) differs from the size of the local file ([0;36m[1m10.84 GB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-01 09:10:42[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 06:50:23[22m[0;39m), and the ETag of the remote file ([0;36m[1m43c047b7d3f486a9fbb6db51cb0f6f4a[22m[0;39m) differs from the ETag of the local file ([0;36m[1me5037db4b86f843d1a6937ac723ce62a[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/base.py:263
WARNING - 2021-08-02 10:56:06,301 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:135
ERROR - 2021-08-02 10:56:08,436 - common.dbase - dbase.execute_update - MainThread - Exception OperationalError with message: near "WHERE": syntax error in /Users/rkrivov/PycharmProjects/s3_upload/common/dbase.py:814
WARNING - 2021-08-02 10:59:22,238 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:135
CRITICAL - 2021-08-02 14:07:57,243 - __main__ - parallels.main - MainThread - Exception ImportError with message "cannot import name 'S3Object' from partially initialized module 's3._base._object' (most likely due to a circular import) (/Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_object.py)" is not caught in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:103
Stack (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 2173, in <module>
    main()
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 2164, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1476, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/rkrivov/PycharmProjects/s3_upload/parallels.py", line 115, in <module>
    main()
  File "/Users/rkrivov/PycharmProjects/s3_upload/parallels.py", line 103, in main
    logger.critical(
WARNING - 2021-08-02 14:24:49,483 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:102
WARNING - 2021-08-02 14:49:45,919 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:95
WARNING - 2021-08-02 14:52:21,286 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:95
WARNING - 2021-08-02 14:55:03,123 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:95
WARNING - 2021-08-02 14:58:41,948 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/config.pvs[4m[0;39m was changed: The size of the remote file ([0;36m[1m33.10 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m33.10 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-02 06:52:49[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 11:58:21[22m[0;39m), and the ETag of the remote file ([0;36m[1m7809c5caaee28288582c01fa1deb4035[22m[0;39m) differs from the ETag of the local file ([0;36m[1maa3d659a7b294b25dd96895bbed69380[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-02 14:58:41,962 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/statistic.log[4m[0;39m was changed: The size of the remote file ([0;36m[1m3.70 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m3.70 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-02 06:52:49[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 11:58:21[22m[0;39m), and the ETag of the remote file ([0;36m[1m9cc3e03874af7fd107dca3e9c270e9b3[22m[0;39m) differs from the ETag of the local file ([0;36m[1mc6306fd9112486c456e6db497fb8d948[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-02 14:58:41,964 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/config.pvs.backup[4m[0;39m was changed: The size of the remote file ([0;36m[1m33.10 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m33.10 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-02 06:52:49[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 11:58:21[22m[0;39m), and the ETag of the remote file ([0;36m[1m7809c5caaee28288582c01fa1deb4035[22m[0;39m) differs from the ETag of the local file ([0;36m[1maa3d659a7b294b25dd96895bbed69380[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-02 14:58:41,997 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/parallels.log[4m[0;39m was changed: The size of the remote file ([0;36m[1m8.69 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m8.96 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-02 06:52:50[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 11:58:21[22m[0;39m), and the ETag of the remote file ([0;36m[1m0d4d61b14d810e0b53216ff8c6476568[22m[0;39m) differs from the ETag of the local file ([0;36m[1m4f707993e570416e74b0316bda941e53[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-02 15:03:17,055 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/config.pvs[4m[0;39m was changed: The size of the remote file ([0;36m[1m33.10 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m33.10 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-02 06:52:49[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 12:03:01[22m[0;39m), and the ETag of the remote file ([0;36m[1m7809c5caaee28288582c01fa1deb4035[22m[0;39m) differs from the ETag of the local file ([0;36m[1m46b693f59fbacab796d01caaf20e34de[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-02 15:03:17,069 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/statistic.log[4m[0;39m was changed: The size of the remote file ([0;36m[1m3.70 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m3.70 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-02 06:52:49[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 12:03:01[22m[0;39m), and the ETag of the remote file ([0;36m[1m9cc3e03874af7fd107dca3e9c270e9b3[22m[0;39m) differs from the ETag of the local file ([0;36m[1ma7896af013028936c01564f14c367944[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-02 15:03:17,071 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/config.pvs.backup[4m[0;39m was changed: The size of the remote file ([0;36m[1m33.10 KB[22m[0;39m) differs from the size of the local file ([0;36m[1m33.10 KB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-02 06:52:49[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 12:03:01[22m[0;39m), and the ETag of the remote file ([0;36m[1m7809c5caaee28288582c01fa1deb4035[22m[0;39m) differs from the ETag of the local file ([0;36m[1m46b693f59fbacab796d01caaf20e34de[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-02 15:03:17,102 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/parallels.log[4m[0;39m was changed: The size of the remote file ([0;36m[1m8.69 MB[22m[0;39m) differs from the size of the local file ([0;36m[1m9.03 MB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-02 06:52:50[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 12:03:00[22m[0;39m), and the ETag of the remote file ([0;36m[1m0d4d61b14d810e0b53216ff8c6476568[22m[0;39m) differs from the ETag of the local file ([0;36m[1mc5721203e3fde19be28f9babbe135667[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
WARNING - 2021-08-02 15:03:47,332 - s3._base._base - _base._compare_files - MainThread - The file [0;37m[4m/Users/rkrivov/Parallels/Windows 10.pvm/harddisk.hdd/harddisk.hdd.0.{5fbaabe3-6958-40ff-92a7-860e329aab41}.hds[4m[0;39m was changed: The size of the remote file ([0;36m[1m10.84 GB[22m[0;39m) differs from the size of the local file ([0;36m[1m12.05 GB[22m[0;39m), and the time when the remote file was last modified ([0;36m[1m2021-08-02 07:08:48[22m[0;39m) differs from the time when the local file was last modified ([0;36m[1m2021-08-02 12:03:00[22m[0;39m), and the ETag of the remote file ([0;36m[1me5037db4b86f843d1a6937ac723ce62a[22m[0;39m) differs from the ETag of the local file ([0;36m[1mccf6395dd85d4db45f6aa29c35b4db26[22m[0;39m) in /Users/rkrivov/PycharmProjects/s3_upload/s3/_base/_base.py:269
ERROR - 2021-08-02 15:05:19,439 - common.dbase - dbase.execute_update - MainThread - Exception IntegrityError with message: UNIQUE constraint failed: virtual_machines.uuid in /Users/rkrivov/PycharmProjects/s3_upload/common/dbase.py:822
WARNING - 2021-08-02 15:08:00,864 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:95
ERROR - 2021-08-02 15:08:11,631 - common.dbase - dbase.execute_update - MainThread - Exception IntegrityError with message: UNIQUE constraint failed: virtual_machines.uuid in /Users/rkrivov/PycharmProjects/s3_upload/common/dbase.py:822
ERROR - 2021-08-02 15:10:55,574 - common.dbase - dbase.execute_update - MainThread - Exception IntegrityError with message: UNIQUE constraint failed: virtual_machines.uuid in /Users/rkrivov/PycharmProjects/s3_upload/common/dbase.py:822
WARNING - 2021-08-02 15:17:12,844 - __main__ - parallels.main - MainThread - User terminate program! in /Users/rkrivov/PycharmProjects/s3_upload/parallels.py:95
